=== glonardoni/incubated/SMARTMANUFACTURING/dataModel.PredictiveMaintenance/MaintenanceSkill/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "MaintenanceSkill",
    "type": "object",
    "properties": {
        "skillID": {
            "type": "string",
            "description": "Property. Unique identifier for the skill."
        },
        "skillName": {
            "type": "string",
            "description": "Property. Name of the skill."
        },
        "skillDifficulty": {
            "type": "string",
            "description": "Property. Difficulty of the skill."
        },
        "description": {
            "type": "string",
            "description": "Property. Description of the skill."
        },
        "requiredTool": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Property. List of tools required for the skill."
        }
    },
    "required": [
        "skillID",
        "skillName"
    ]
}

=== glonardoni/incubated/SMARTMANUFACTURING/dataModel.PredictiveMaintenance/MaintenanceSkill/examples/example.json
{
    "skillID": "SK001",
    "skillName": "Engine Repair",
    "skillDifficulty": "Advanced",
    "description": "This skill involves diagnosing and repairing engine issues in vehicles.",
    "requiredTool": [
        "Wrench Set",
        "Socket Set",
        "OBD-II Scanner",
        "Jack and Jack Stands"
    ]
}
